modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power"
version="1.0.0.11"
displayName="Keepers of the Stones II"
displayURL="https://power-umc.ru/minecraft-java-edition/mods/6-keepers-of-the-stones.html"
logoFile="logo.png"
credits="Created by Environment Studios"
authors="Environment Studios"
description="Keepers of the Stones II is a mod created as a continuation of the original version of the Keepers of the Stones mod. It adds 48 new elemental stones that can be used to improve the character's skills and powers."

[[dependencies.power]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="playeranimator"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="bettercombat"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

