# Automatically builds and publishes the mod when a new release is created on GitHub.
# It uploads the mod to GitHub, CurseForge and Modrinth.

name: Beta

on:
  push:
    branches:
      - "beta"
env:                                              
  MINECRAFT_VERSION: 1.20.1                       
  JAVA_VERSION: 17      
  VERSION: 1.0.0.7
  RELEASE_NAME: Keepers of the Stones II 1.0.0.7 Beta

jobs:
  build:
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish mod to CurseForge and Modrinth
        id: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 906406
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: hKbKT6ME
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: beta
          changelog-file: BETA_CHANGELOG.md                                      

          loaders: forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          modrinth-featured: false
          fail-mode: warn	
          
      - name: Send Discord webhook
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "@everyone"
        env:
          DISCORD_WEBHOOK: "${{secrets.DISCORD_WEBHOOK}}"
          DISCORD_EMBEDS: |
            [{
              "title": "${{env.RELEASE_NAME}} for Minecraft ${{env.MINECRAFT_VERSION}} Released",
              "color": 14177041,
              "thumbnail": {
                "url": "https://sun9-26.userapi.com/impg/tONr8xsZxwJhkVbeV9nLh6WJTT9JL5yeGTzw0A/khlieuPeAJk.jpg?size=1920x1080&quality=96&sign=1c071ed8ac91a735a11fb8079707b499&type=album"
              },
              "url": "https://www.curseforge.com/minecraft/mc-mods/keepers-of-the-stones-ii",
              "fields": [
                  {
                    "name": "Download now:",
                    "value": "[<:curseforge:805066577871110196> CurseForge](https://www.curseforge.com/minecraft/mc-mods/keepers-of-the-stones-ii)\n[<:modrinth:805066578215043092> Modrinth](https://modrinth.com/mod/keepers-of-the-stones-2)\n[<:github:805066578164580392> GitHub](https://github.com/Environment-Studios-Official/Keepers-of-the-Stones-2)",
                    "inline": true
                  }
              ],
              "footer": {
                "text": "Created by the Environment Studios team!",
                "icon_url": "https://sun9-78.userapi.com/impg/kD0AwY7Xis8STJ07eud_fyqAW2-XFMaMsbnmAw/Ew3PdOe0y7Q.jpg?size=2000x2000&quality=95&sign=f990104d07c8be4a20dfa2ed1e4739d2&type=album"
              }
            }]
